### ISSUE TITLE
How do I parse a unit?

### ISSUE THREAD

**Issue by aleppard** [qudtlib/qudtlib-java#52]
Hi,

Thanks for this project! I'm looking at integrating a Java library that does unit parsing and conversion. However, I'm having trouble parsing a unit. If I call: `Qudt.unitFromLabel("lb")` or `Qudt.unitFromLocalname("lb")` neither of them return a value. Am I doing something wrong?

thanks,
Andrew

**Comment by fkleedorfer** [comment]
The labels checked in that method are the rdf:label values of the unit.

See https://qudt.org/vocab/unit/LB

If you know the unit at compile time, you can use Qudt.Units.LB

If not, you could iterate over all units and filter by eg ucumcode or symbol

**Comment by fkleedorfer** [comment]
Qudt.unitFromLocalname("LB") should work too

**Comment by aleppard** [comment]
Awesome! Both of those work nicely - I think the iteration solution will work best for me. Thanks for the project and your help.

I would suggest making unitFromLocalname() case insensitive but I'm not sure that is the right call for all symbols.

**Comment by fkleedorfer** [comment]
If you look at the implementation of unitFromLocalname, you'll see that that is not an easy fix. However, making a string matching method for units, providing the best matches in a list, has been on my mind. How do you obtain units in your use case? Ie, where did that 'lb' string come from?

**Comment by aleppard** [comment]
[This is the project I'm working on](https://github.com/aleppard/argus). The strings come from text the user might type, e.g. "pounds in kgs", "1/4 pound in grams", "oz in lb", "mph to kph", "100C in F" etc. So iterating through the list and finding the best match sounds like a good option for me.

**Comment by fkleedorfer** [comment]
Ok I'll think about it. Maybe you could create an issue describing what you need, and 'll resolve it when it (ever) gets done? 

Also, there is a js version of qudtlib so you could do all that in the browser if you wanted 

Am 19. Februar 2023 02:11:25 MEZ schrieb Andrew Leppard ***@***.***>:
>[This is the project I'm working on](https://github.com/aleppard/argus). The strings come from text the user might type, e.g. "pounds in kgs", "1/4 pound in grams", "oz in lb", "mph to kph", "100C in F" etc. So iterating through the list and finding the best match sounds like a good option for me.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/qudtlib/qudtlib-java/issues/52#issuecomment-1435806880
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by aleppard** [comment]
No need. I have everything I need to write that functionality myself. I will make the code available in case you want to fold it back into your project.

**Comment by aleppard** [comment]
Hi,

I wrote a basic unit parser wrapping around your library:

[Unit Parser](https://github.com/aleppard/argus/blob/main/src/main/java/com/argus/resolver/UnitParser.java)
[Unit Parser Unit Test](https://github.com/aleppard/argus/blob/main/src/test/java/com/argus/resolver/UnitParserTest.java)

It's far from perfect but it's a start.

Feel free to build on and integrate this code into your project under whatever license you wish.

One problem I had is that I couldn't get lower-case "lb" from this project, even though it's in the [ontology](https://qudt.org/vocab/unit/LB) under qudt:udunitsCode. Is there a function in your library that I missed to get this? Thanks!

**Comment by fkleedorfer** [comment]
Hi, sorry for the late reply!

Thanks for the contribution - not sure at this point if, how, where or when to integrate but now there's a starting point. The qudt:udunitsCode is not being generated from qudt currently. I haven't looked into the data but I am pretty sure generating that property would just be along the lines of how other unit properties are generated, so not too difficult, but would have to be done for the Java and the typescript version. If you could prepare a PR that does it, it would certainly help!
