### ISSUE TITLE
Unit descriptions

### ISSUE THREAD

**Issue by akram-hameed** [qudtlib/qudtlib-java#95]
As per the README, raising an issue regarding the availability of descriptions on Unit. Specifically, the `dcterms:description`. Is there any appetite to add this to your official codebase?

**Comment by fkleedorfer** [comment]
Without a need for it and out of concern for library size, I have refrained from it so far. I guess we can  add it. Could you please describe your use case?

**Comment by steveraysteveray** [comment]
@fkleedorfer, in the context of descriptions, I just wanted to give you a heads up that QUDT is in the process of modifying the Latex delimiter for all embedded Latex (including descriptions), from \\\\( and \\\\) to $ (see our branch rh-latex-fixes-cusp1). Depending on what you do with descriptions, I didn't want this to catch you off guard.

**Comment by fkleedorfer** [comment]
Thanks, @steveraysteveray!

**Comment by fkleedorfer** [comment]
... Really depends on @akram-hameed 's use case. So far, nobody else has asked.

**Comment by akram-hameed** [comment]
Hi @fkleedorfer - sorry for the delay in responding. The use-case is quite simple: we're using the qudtlib-java to generate metadata for reporting by API to users. These users have a need to assign a unit to a stream of data to aid in how consumers of data interpret that data at a later date. Having the description (official, released description) available would aid in providing contextual help to consumers of the API, as well as consumers of our user interface. If the size truly is an issue, I'll pull the descriptions with SPARQL from the official RDF and knock something together to sit alongside your library I suppose.

**Comment by fkleedorfer** [comment]
Thanks! If I add the description, how would you prefer the latex strings handled? Easiest for me of course is to just to keep them as is.
 
Regarding size, I was thinking of putting the descriptions in a separate jar

**Comment by fkleedorfer** [comment]
I've decided to add a description field to Unit, QuantityKind and PhysicalConstant. If lib size becomes a problem, we can deal with it then.

**Comment by fkleedorfer** [comment]
No fancy processing of the string, though. just the string value.

**Comment by fkleedorfer** [comment]
Will be part of 6.5.0 - to be released later today.

**Comment by akram-hameed** [comment]
Thanks @fkleedorfer , much appreciated!

**Comment by akram-hameed** [comment]
Sorry for necromancy here, but tiny helpful note for anyone who comes along later - if your jacoco blows up after using the new 6.5.0 due to 'class too large', you will need to exclude the qudtlib-java class in question from your inspections.

**Comment by fkleedorfer** [comment]
You might want to add that to the readme
